CREATE TABLE IF NOT EXISTS board_members (
  id SERIAL PRIMARY KEY,
  board_id INTEGER NOT NULL REFERENCES boards (id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  UNIQUE (board_id, user_id)
);

CREATE TABLE IF NOT EXISTS board_invites (
  id SERIAL PRIMARY KEY,
  board_id INTEGER NOT NULL REFERENCES boards (id) ON DELETE CASCADE,
  token TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
